### PR TITLE
Custom css

### PR DESCRIPTION
**Pull request by Abubakar101**

### CODE REVIEW

**Comment by Asher978** [comment]
CSS looks great!!

Questions about the calendar:

1. Is it currently set on your google account?
2. How can you create events? Directly through your calendar?
3. Also the links of events on the date... i dont think we should have them enabled because it redirects to google calendar. Bit odd for a USER. If the USER clicks on that event it redirects them to their google calendar... what you think?

**Comment by Abubakar101** [comment]
Yes the calendar is connected to my Gmail account and right now, we need to go to our Google calendar to make the chances, but I am sure we should be able to make changes right on the website. When we hand them the website, we need to replace my Gmail account with theirs.....

**Comment by Asher978** [comment]
@halo123u Do we want to give them an option to add calendar events from the website or their CMS page? Or should they just add via Google Calendar?

**Comment by Abubakar101** [comment]
@Asher978 I think there is an option to edit the calendar right from their website. They don't need to go to their Google Calendar. BTW, I am using Google Calendar API and then sending data to Fullcalendar plugin because Fullcalendar is very customizable. Here it says that events can be modified - https://fullcalendar.io/docs/event_ui/editable/

**Comment by Asher978** [comment]
@Abubakar101 
Calendar Page: Minor CSS changes

Closure and Events Subheadings at the bottom need to follow the color per wireframes. 
Also the calendar size needs to be condensed a bit. Currently it takes the view width of the page. Wire frames have the size of the calendar a little smaller.

**Comment by Abubakar101** [comment]
We aren't using calendar wireframe anymore, UX team said to work with them together in person - perhaps on Wednesday or Thursday.

**Pull request merged**
